### ISSUE TITLE
Page could not load

### ISSUE THREAD

**Issue by dabelle** [neothematrix/noip-renew#33] opened 2022-08-17 03:24 UTC
Got the following message when running noiprenew-{USER}

[2022/08/16 23:22:10] - Debug level: 2
[2022/08/16 23:22:10] - Opening https://www.noip.com/login...
[2022/08/16 23:22:14] - Logging in...
[2022/08/16 23:22:25] - my.noip.com page could not load

**Comment by neothematrix** [comment] 2022-08-17 08:07
check your username and password, any details in the debug1.png, debug2.png or execption.png files?

**Comment by Angel0ffDeath** [comment] 2022-08-18 05:40
@neothematrix This message appears after successful login. Probably element noip-cart changed. Must check the page

**Comment by PrivatePasta** [comment] 2022-08-25 20:25
Facing the same issue

**Comment by Angel0ffDeath** [comment] 2022-08-28 10:43
@neothematrix Soleved. Pull request created

**Comment by neothematrix** [comment] 2022-08-29 11:47
mmm ok I'll try to test the changes also in my scenario. Currently the script is working fine for me, so before introducing a change I'd like to replicate the issue.
@Angel0ffDeath were you having issues too?

**Comment by Angel0ffDeath** [comment] 2022-08-30 08:35
@neothematrix I didn't tried it without changes, but after login browser loads automatically https://my.noip.com/ and not https://my.noip.com/dynamic-dns
So I just added loading opening the correct page and corresponding loggin

**Comment by neothematrix** [comment] 2022-08-30 13:28
ok, it's weird because the script is still working fine for me, even without changes.
@dabelle @PrivatePasta can you please give us your feedback? is the script as it is working for you? If not, can you try with the changes proposed by @Angel0ffDeath ?

**Comment by PrivatePasta** [comment] 2022-09-03 12:53
So this is weird, I tried both repo's and have issues on both. The @neothematrix repo exits with `my.noip.com page could not load`. Logfile is empty and the exception.png says the username/password combination is incorrect. The @Angel0ffDeath repo exits with the following:
```
[2022/09/03 12:48:56] - Message: no such element: Unable to locate element: {"method":"xpath","selector":"//form[@id='clogs']/input[@name='username']"} (Session info: headless chrome=105.0.5195.52)
Stacktrace:
#0 0xaaaae2bf05c4 <unknown>
#1 0xaaaae2a2a784 <unknown>
#2 0xaaaae2a5b6fc <unknown>
#3 0xaaaae2a85f6c <unknown>
#4 0xaaaae2a50848 <unknown>
#5 0xaaaae2c32bc4 <unknown>
#6 0xaaaae2c34f00 <unknown>
#7 0xaaaae2c35460 <unknown>
#8 0xaaaae2c1ec44 <unknown>
#9 0xaaaae2c35a44 <unknown>
#10 0xaaaae2c13758 <unknown>
#11 0xaaaae2c4f6f8 <unknown>
#12 0xaaaae2c4f86c <unknown>
#13 0xaaaae2c6859c <unknown>
#14 0xffffaeac0624 <unknown>
#15 0xffffae5f049c <unknown>
```
Again logfile is empty but the exception.png doesn't say anything. Uploading them here anyway.
[neothematrix - debug1.png](https://am0g.us/OwPzPnhE)
[neothematrix - exception.png](https://am0g.us/ZVsoq5DC)
[Angel0ffDeath - debug1.png](https://am0g.us/3Ju4JFZB)
[Angel0ffDeath - exception.png](https://am0g.us/WqPAoWTC)

**Comment by drsurfer** [comment] 2022-09-03 13:27
@neothematrix on my RPi all is working as usual, and in a fresh installation on a brand new system, too

**Comment by neothematrix** [comment] 2022-09-04 07:28
Thank you a for your feedbacks.
@PrivatePasta, just to understand, has the script been working for you before or is this the first time you're setting it up? 
It's very likely your password might be incorrect. The most common issue is that the python script expects the password parameter to be base64 encoded, this is done automatically if you use the setup.sh script, if you're running the python directly, make sure the password parameter is your base64 encoded password, if you're using the generated sh, make sure the password parameter inside that script is also your correctly base64 encoded password, you can always un encode the string to see if it matches your actual password: bas64 -d <encoded pass>

**Comment by neothematrix** [comment] 2022-09-16 13:50
I'm closing this as not reproduce-able, feel free to open a new ticket

**Closed by neothematrix** 2022-09-16 13:50 UTC
