### ISSUE TITLE
Error installing on rpi

### ISSUE THREAD

**Issue by viseniv** [neothematrix/noip-renew#51] opened 2024-02-04 22:09 UTC
Wen y try to run the setup.sh i get this error.

The following packages were automatically installed and are no longer required:
  chromium-common libevent-2.1-7 libjsoncpp25 libminizip1 libopenh264-7
  libopenjp2-7 libsnappy1v5 libwebpdemux2 libwebpmux3 libwoff1 libxnvctrl0
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**Comment by neothematrix** [comment] 2024-02-05 16:49
ciao and thanks for the report.
I can't test the install script on RPI, but try commenting out line 40 of setup.sh:

`$SUDO $PYTHON -m pip install selenium`

and add after line "90", this:

`$SUDO apt -y install $PYTHON-selenium`

**Comment by Angel0ffDeath** [comment] 2024-02-05 19:15
@viseniv Will check this tomorrow, but probably script is a little bit outdated (setup.sh)
First update your pi manually - update,upgrade,autoremove, then skip this step in setup.sh. Install selenium manually via pip3 install selenium==version (check first python3 requirements - @neothematrix thanks for merging my PR). Selenium version should be not greater than 4.10.0.
Then run setup.sh. If there are problems, please post full output from setup.sh and not the error only

**Comment by Angel0ffDeath** [comment] 2024-02-06 17:03
Im not able to reproduce your error. Everything is working by me. Either try suggestions above or post the full output from setup.sh, but according to me the problem is with selenium installation.

**Comment by Angel0ffDeath** [comment] 2024-02-10 08:36
@viseniv I tested today setup.sh few times while playing with selenium versions. Everything is ok by me.

**Comment by Angel0ffDeath** [comment] 2024-02-10 21:51
@neothematrix If there is no more info from @viseniv, I would recommend to close this issue... Give some more days though...

**Comment by neothematrix** [comment] 2024-02-11 08:41
thanks @Angel0ffDeath, actually I had the same error while building the docker images using latest debian release, I think it might be something that changed in recent debian version (bookworm?). Raspberry OS is based on debian right? perhaps @viseniv is using one of the latest version of raspberry OS based on debian bookworm and you tests @Angel0ffDeath were based on the previous version?

**Comment by Angel0ffDeath** [comment] 2024-02-11 13:28
@neothematrix 1. Yes Raspberry OS is based on debian. 2. For the tests I used clean installation of Raspberry OS light on a headless pi 4 with 4G RAM. Raspberry OS version is bullseye - kernel version 6.1.21-v8+

**Comment by neothematrix** [comment] 2024-02-12 10:35
yup, bookworm is debian 12 and the issue seems to be with that version:
the setup.sh installs selenium via "pip" (not apt) and bookworm debian complains that the correct way to install it would be to use an official debian package instead via "apt install python3-selenum".
However, reading the code comments, it seems in the past it was decided to use "pip" installation of selenium because the version of selenium provided by debian 9 official apt packages was too outdated for the script.

**Comment by Angel0ffDeath** [comment] 2024-02-12 20:15
@neothematrix try to change selenium installation with sudo pip3 install selenium. On bullseye it works
I have old pi's running previous versions (debian 9 and 10 and acan test it)

**Closed** 2024-05-02 23:42 UTC
