### ISSUE TITLE
Script does not seem to work now

### ISSUE THREAD

**Issue by KillaOfDawn** [neothematrix/noip-renew#37] opened 2022-11-21 21:55 UTC
No-IP seem to have added a captcha after confirming DNS hostnames which needs to be clicked through to finally renew the domain names.

**Comment by suhiymof** [comment] 2022-11-22 03:23
yes, the script need to be update, anyone know how to fix it?

**Comment by Angel0ffDeath** [comment] 2022-11-22 08:57
@KillaOfDawn @suhiymof Unfortunately I cannot see this screen now. Will be able to see it after 11 days. If somebody can send screen shots and save the page as html just before clicking this new button and send the code, I can try to do something

**Comment by KillaOfDawn** [comment] 2022-11-22 11:41
Hi @Angel0ffDeath,

I've got some screenshots and HTML which I will attach here (the HTML files are in a zip: [NoIPRenew.zip](https://github.com/neothematrix/noip-renew/files/10067007/NoIPRenew.zip)). The work flow for renewing the hostname is now:

1.  Click the usual confirm button on hostnames page.
2.  A page opens confirming whether you want to upgrade to Enhanced Dynamic DNS (Page1.html and Page1.png). You click the "No thanks, just renew my free hostname" button.

![Page1](https://user-images.githubusercontent.com/71264946/203304357-1c4b1667-90f3-4657-8846-98bbf3b02557.png)

3. You are shown a "Would you like to keep your hostname active?" page with a captcha where you have to solve/click the captcha and then the "Confirm your hostname now" button. I've redacted all my files as this shows the hostname you want to confirm. (Page2.html, Page2.png) 

![Page2](https://user-images.githubusercontent.com/71264946/203304813-7d94f86b-f187-4547-8f07-f591d41662b5.png)

4. You are shown a "Update Successful" page which details which hostname has been confirmed (again this is redacted) (Page3-Success.html and Page3-Success.png)

![Page3-Success](https://user-images.githubusercontent.com/71264946/203305078-14fd37b5-eead-496f-a6cd-f24d0f60d4f7.png)

**Comment by neothematrix** [comment] 2022-11-22 11:51
ciao @KillaOfDawn 
thanks for the report and screenshot.
As @Angel0ffDeath I also can't check this as my domains won't require renewal for a few more days.

Just a comment, by your screenshots it seems you're trying to confirm your domain without logging in, probably you did this just for the sake of producing the screenshot, but  just to be clear, No-Ip has always requested captcha to confirm the hostname UNLESS you were logged in.
Maybe now it's too late, but can you confirm captcha is shown in order to confirm the hostname even after logging in?
To be even more clear, this script doesn't click on the "renewal" link received by email, but it just goes through the login page, list of dns, and clicks through any hostname showing the "renew" button, so this is the process you should follow in order to produce the screenshots.
Also, logs and png of failing script runs due to this change would be appreciated.

thanks!

**Comment by KillaOfDawn** [comment] 2022-11-22 12:33
Hey @neothematrix,

Yes I should have clarified, the screenshots above are from the email however, because my domains no longer require renewing I could not access this from the authenticated page. However, the workflow yesterday seemed to be exactly the same as the above when confirming once authenticated on the actual page, I'm fairly certain of this but again, happy to wait until you can see for yourselves as I don't want you wasting time on a wild goose chase in case I've made an error :)

Please find my logs and pngs in the zip: 

[Results.zip](https://github.com/neothematrix/noip-renew/files/10067377/Results.zip)

**Comment by suhiymof** [comment] 2022-11-22 16:12
@neothematrix if this would be helpful？ I have a hostname need to be confirm.
![image](https://user-images.githubusercontent.com/8465498/203364456-72efb773-0789-43ac-827b-60978aa5ee62.png)

**Comment by suhiymof** [comment] 2022-11-22 16:47
@neothematrix @Angel0ffDeath 
![image](https://user-images.githubusercontent.com/8465498/203365776-e121f903-a8ee-4a8f-8a86-184c920cec63.png)
![image](https://user-images.githubusercontent.com/8465498/203370898-74ae7b53-fe6f-4b4a-ac35-21d382bd6670.png)
![image](https://user-images.githubusercontent.com/8465498/203371248-76843b6f-b2c0-4611-a710-2c9d67ec48a0.png)
[noip.zip](https://github.com/neothematrix/noip-renew/files/10069383/noip.zip)

**Comment by suhiymof** [comment] 2022-11-22 16:49
@neothematrix @Angel0ffDeath I uploaded the png screen on the pre comment , the HTML files are in  [noip.zip](https://github.com/neothematrix/noip-renew/files/10069383/noip.zip)

**Comment by Angel0ffDeath** [comment] 2022-11-23 09:27
@KillaOfDawn Something not clear for me - According to you the script doesnt work, but your log shows everything is ok and host confirmed???

**Comment by solaireofastora20** [comment] 2022-11-23 19:10
@Angel0ffDeath so this confused me too, its also why I wasnt alerted that the script didnt work and my domain actually expired in the end.

Yes it may be that i was running an older version as I downloaded it a few months ago however because I saw the captcha when going to renew manually I decided to create this issue.

Again yes the log is older as I hadnt realised the script hadnt worked and I received an email that my domain had expired which is what alerted me.

**Comment by KillaOfDawn** [comment] 2022-11-23 19:30
Hi @Angel0ffDeath,

This is what also confused me. I have an alert generated and sent to me when the script does not run correctly however, as the script reported it worked successfully, I did not receive this alert.

I also downloaded the script some months ago which will be why its not the most up to date version so I'm happy to wait until someone else confirms with the newest version of the script.

The log was 3 days older as it ran a few days before hand and then I only realised it didnt successfully renew when I received an email stating my domain was expired.

**Comment by Angel0ffDeath** [comment] 2022-11-24 07:22
@KillaOfDawn Ok. Now I understand. So the script reports everything is ok, but doesnt confirms the host
@AHIOS Yes try the latest script with debug level 2 and post the log with all debug pictures

**Comment by AHIOS** [comment] 2022-11-24 09:56
I'm struggling trying to run the script on my M1 Mac Ventura: here the logs.
sh setup.sh
No-IP Auto Renewal Script Setup.
1) Install/Repair Script	    3) Uninstall Script
2) Update noip.com account details  4) Exit setup.sh
Select an option: 2
Enter your No-IP Account details...
Username: *********
Password: 
sed: 1: "/usr/local/bin/noip-ren ...": extra characters at the end of l command

Anyway i would finally run it on my raspberry pi (1st version) but others errors here:
sh setup.sh 
setup.sh: 6: [: pi: unexpected operator
setup.sh: 19: setup.sh: Syntax error: "(" unexpected

@Angel0ffDeath 
Could you please try to adapt the script to run at least on one of my machine so I can try to extract some logs and screens?

**Comment by Angel0ffDeath** [comment] 2022-11-24 19:11
@AHIOS Sorry, Im not familiar with M1 Mac Ventura.
For RPi first edition - please specify which linux distro you are running. You need Python 3.6 at least to run the script. To run the script on Python 3.5 - read the other issue, I opened.
For more support, please post the full output from setup.sh and/or python script.

**Comment by AHIOS** [comment] 2022-11-27 18:20
Hi @Angel0ffDeath , 
I tried installing the latest version of python and selenium on my raspi, and tried writing a hello world script but it doesn't work (the browser seems to close before I can do anything).
So I tried writing a js with apple shortcuts, and I will try to get phantom js or something similar working on my raspi.
Anyway if it helps here is how I retrieve and simulate the interaction with the page for renew (I DID NOT MEET ANY CAPTCHA!!!):

```
var usrNameField = document.querySelector("#username");
usrNameField.value="YOUR_USERNAME_HERE";
var pwdField = document.querySelector("#password");
pwdField.value="YOUR_PASSWORD_HERE";
var submitBtn = document.querySelector("#clogs-captcha-button");
submitBtn.click();

WAIT UNTIL PAGE LOADS

var hostnamesDiv = document.querySelector(".link-info.pull-left.d-block.cursor-pointer");
hostnamesDiv.click();

var confirmBtn = document.querySelector(".btn.btn-labeled.btn-success");
confirmBtn.click();
```

My ip has been banned, but in the various attempts I seem to have managed to renew my hostnames (the renew button is gone from one hostname)

I will continue juggling in a month at the next renewal and let you know.
For now, I hope the pesudocode (the querySelectors) above could be useful to someone.

**Comment by neothematrix** [comment] 2022-11-29 10:28
ciao all,
just FYI, one of my domain was renewed without any issue yesterday by the script, no captcha or anything, the script run as usual and renewed it.
Keep in mind that if you do many login/tests your account will be banned temporarily or sometimes additional captcha are requested, this could be the explanation of the issues you're experiencing?
@Angel0ffDeath have you been able to check if your domain was correctly renewed?

**Comment by Angel0ffDeath** [comment] 2022-11-30 17:35
@neothematrix I will be able to test the script this Saturday (Dec 3rd). Will report the result.

**Comment by Angel0ffDeath** [comment] 2022-12-02 23:06
@neothematrix @AHIOS @suhiymof @KillaOfDawn 

I can confirm last version of the script works perfect as it is. One of my hosts renewed successfully without any additional intervention from me.

To all who has problems - please use the latest version of the script.
If you use older version of the script, before opening an issue, please try with the latest version. It is very probable older versions to NOT work properly due to a different reasons. Actually this is the reason there are new versions - we try to keep script working :).

I suggest this issue to be closed.

**Comment by neothematrix** [comment] 2022-12-03 08:36
thanks @Angel0ffDeath I'll close this

**Closed by neothematrix** 2022-12-03 08:36 UTC
